name: testdata-lint
on: workflow_dispatch
jobs:
  build:
    name: Check Testdata
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint Testdata
      run: make testdata-lint
      working-directory: v3
